### ISSUE TITLE
Colour Theme

### ISSUE THREAD

**Issue by grellyd** [CodeTheChangeUBC/ctc_site#1]
The site currently has a garish colour combo from my experimentation.

We need a solid and consistent colour theme implemented through the entire site. This should be implemented in the CSS, and appropriate for our group. A nice site to find colour palettes is  [http://colorhunt.co](url) from which I have seen and liked [http://colorhunt.co/c/9385](url), [http://colorhunt.co/c/32519](url), and [http://colorhunt.co/c/42937](url). The current CSS file in app/assets/stylesheets/home.scss has the four colours implemented as CSS variables for easy swapping in and out.

**Comment by bchugg** [comment]
Not that I'm any authority on making things look awesome - but I can definitely do some work on this.

**Comment by bchugg** [comment]
@grellyd Would you consider this done?
