### ISSUE TITLE
Layout of different sections of the home page && A grid style display for the Team members ?

### ISSUE THREAD

**Issue by AriYV** [CodeTheChangeUBC/ctc_site#14]

**Comment by bchugg** [comment]
@AriYV is there a question?

**Comment by AriYV** [comment]
Would a grid (different from the project section), be a good idea for the team part of the page. @bchugg

**Comment by AriYV** [comment]
I'll commit with the changes tonight, you and @grellyd  can have a looksie and let me know.

**Comment by bchugg** [comment]
Cool, sounds good! You have better styling judgement than me I think haha, so I trust your judgement. Remember to commit to a separate branch and submit a pull-request.

**Comment by grellyd** [comment]
Thanks for doing the styling @AriYV

**Comment by AriYV** [comment]
Hey folks, the changes I made are up on my(profile) repo. Ari-sty. I'll push them tomorrow, I'm having some troubles with my laptop. Night!
