### ISSUE TITLE
Adaptive Header

### ISSUE THREAD

**Issue by grellyd** [CodeTheChangeUBC/ctc_site#2]
When on the home page, the header appropriately links/jumps to lower portions of the page to avoid page loads and keep the viewer engaged. However when on other pages (root/login etc.), when they click on "About" the button should take them to root/about instead of root/login#about.

This will require a ruby script in the header based on the current page, to dynamically change the header behaviour. This is noted by a TODO in app/views/layouts/_header.html.erb

**Comment by bchugg** [comment]
@grellyd @AriYV We should figure out the full behaviour of the header before we tackle this maybe. Do we want drop downs or anything or is the dynamic routing the way to go?
