### ISSUE TITLE
Detailed About Page

### ISSUE THREAD

**Issue by grellyd** [CodeTheChangeUBC/ctc_site#3]
We need to fully implement a detailed about page for the user who wants to read deeply about our organisation, beyond the basic info provided on the root page.

**Comment by bchugg** [comment]
@grellyd What kind of info are you thinking goes on this page? Do we have enough content/info yet?

**Comment by AriYV** [comment]
What I did was, give the page a basic layout with some photos, content of the written material not known yet.
