### ISSUE TITLE
Home Logo Does not return on Home Navigaton

### ISSUE THREAD

**Issue by grellyd** [CodeTheChangeUBC/ctc_site#48]
@EWaterman After merging #46 into master, noticed the following error.

![tmp](https://cloud.githubusercontent.com/assets/7812612/20690785/839c664e-b5c4-11e6-9a33-f1409bd05aae.png)

To replicate, go to home page at https://ctc-site-test.herokuapp.com/ then scroll down and click "Members". Once there, click the top left logo to return to home. The main logo does not appear again.

**Comment by bchugg** [comment]
@grellyd See #41 . This issue should be fixe by pull request #47
